#!/bin/bash
# Registers the Tab Organizer native-messaging host so the extension's
# "Smart group" can call your local `claude` CLI. Re-run any time `claude` or
# `node` moves. macOS only (Chrome/Chromium/Brave/Edge).
set -euo pipefail

HOST_NAME="com.tab_organizer.claude"
EXT_ID="mloknppfnpkobonlnoghijnioohcbnlp"   # pinned via manifest "key"
DIR="$(cd "$(dirname "$0")" && pwd)"

NODE="$(command -v node || true)"
CLAUDE="$(command -v claude || true)"
if [ -z "$NODE" ];   then echo "ERROR: 'node' not found on PATH." >&2; exit 1; fi
if [ -z "$CLAUDE" ]; then echo "ERROR: 'claude' CLI not found on PATH." >&2; exit 1; fi

WRAPPER="$DIR/claude-host.sh"
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by install.sh — launches the host with absolute paths because
# Chrome starts native hosts with a minimal environment.
export CLAUDE_BIN="$CLAUDE"
exec "$NODE" "$DIR/claude_host.js"
EOF
chmod +x "$WRAPPER" "$DIR/claude_host.js"

read -r -d '' MANIFEST <<EOF || true
{
  "name": "$HOST_NAME",
  "description": "Tab Organizer — Claude CLI bridge",
  "path": "$WRAPPER",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF

installed=0
for BASE in \
  "$HOME/Library/Application Support/Google/Chrome" \
  "$HOME/Library/Application Support/Google/Chrome Beta" \
  "$HOME/Library/Application Support/Google/Chrome Canary" \
  "$HOME/Library/Application Support/Chromium" \
  "$HOME/Library/Application Support/BraveSoftware/Brave-Browser" \
  "$HOME/Library/Application Support/Microsoft Edge"; do
  if [ -d "$BASE" ]; then
    TARGET="$BASE/NativeMessagingHosts"
    mkdir -p "$TARGET"
    printf '%s\n' "$MANIFEST" > "$TARGET/$HOST_NAME.json"
    echo "installed -> $TARGET/$HOST_NAME.json"
    installed=$((installed + 1))
  fi
done

echo
echo "node:   $NODE"
echo "claude: $CLAUDE"
echo "ext id: $EXT_ID"
if [ "$installed" -eq 0 ]; then
  echo "WARNING: no supported browser profile dirs found." >&2
else
  echo "Done. Registered for $installed browser(s). Fully quit & reopen the browser, then use Smart group."
fi
